import { caesar, caesarBruteForce, letterFrequencies } from '../crypto/classical.ts';
import { playfair } from '../crypto/playfair.ts';
import { hill, hillMatrix } from '../crypto/hill.ts';
import { desBlock } from '../crypto/des.ts';
import { aesEncryptBlock, bytesToHex, hexToBytes } from '../crypto/aes.ts';
import { sha512Hex } from '../crypto/sha512.ts';
import { hammingDistance } from '../crypto/sha256.ts';
import { rc4 } from '../crypto/stream.ts';
import { cbcEncrypt, ecbEncrypt, pkcs7 } from '../crypto/modes.ts';
import { rsaDecrypt, rsaEncrypt, rsaKeys } from '../crypto/rsa.ts';
import { breakVigenere, cribDrag, factorSmall, repeatedBlocks, xorBytes } from '../crypto/attacks.ts';
import { vigenere } from '../crypto/classical.ts';
import { SAMPLE_ENGLISH } from '../crypto/sample.ts';
import { parseBig } from '../components/common/ui.tsx';

export interface Field { id: string; label: string; def: string; hint?: string }
export interface Line { label: string; value: string }
export type Values = Record<string, string>;
export interface Topic {
  id: string; title: string; category: string; blurb: string; tint: 0 | 1 | 2 | 3 | 4; tall: boolean;
  glyph: () => [string, string]; how: string[]; exampleNote: string; fields: Field[]; run: (v: Values) => Line[] | Promise<Line[]>;
  limits: string; full?: { to: string; label: string }; related: string[];
}
const enc = (s: string) => [...new TextEncoder().encode(s)];
const KEY = '2b7e151628aed2a6abf7158809cf4f3c', BLOCK = '3243f6a8885a308d313198a2e0370734';
const IV = new Array<number>(16).fill(0).map((_, i) => i);

export const TOPICS: Topic[] = [
  { id: 'caesar', title: 'Caesar Cipher', category: 'Classical', blurb: 'Slide every letter along the alphabet by a fixed amount.', tint: 0, tall: false,
    glyph: () => ['HELLO', caesar('HELLO', 3)], how: ['Pick a shift number, the key. 3 is the famous one.', 'Replace each letter with the letter that many places later in the alphabet. After Z, wrap to A.', 'To decrypt, shift the same number of places backwards.'],
    exampleNote: 'Spaces and punctuation stay as they are; upper and lower case are kept.', fields: [{ id: 'text', label: 'Text', def: 'Meet me at noon' }, { id: 'shift', label: 'Shift', def: '3', hint: 'Any whole number; it wraps every 26.' }],
    run: (v) => { if (!/^-?\d+$/.test(v.shift.trim())) throw new Error('Shift must be a whole number such as 3 or -5.'); const n = Number(v.shift); const c = caesar(v.text, n); return [{ label: 'Encrypted', value: c }, { label: 'Decrypted back', value: caesar(c, n, true) }]; },
    limits: 'There are only 25 useful shifts, so anyone can try them all in seconds.', full: { to: '/caesar', label: 'Open the step-by-step visualizer' }, related: ['cryptanalysis', 'playfair'] },
  { id: 'playfair', title: 'Playfair Cipher', category: 'Classical', blurb: 'Encrypts letter pairs using a 5×5 grid built from a keyword.', tint: 3, tall: true,
    glyph: () => ['HIDE', playfair('HIDE', 'PLAYFAIR EXAMPLE').output], how: ['Write the keyword into a 5×5 grid, skip repeated letters, then fill in the rest of the alphabet (I and J share a cell).', 'Split the message into pairs. If a pair repeats a letter, put an X between; if one letter is left over, add an X.', 'Same row: take the letter to the right. Same column: take the letter below. Otherwise take the opposite corners of the rectangle.'],
    exampleNote: 'The classic example from the history books, run through the real implementation.', fields: [{ id: 'key', label: 'Keyword', def: 'PLAYFAIR EXAMPLE' }, { id: 'text', label: 'Message', def: 'Hide the gold in the tree stump' }],
    run: (v) => { const e = playfair(v.text, v.key); const d = playfair(e.output, v.key, true); return [{ label: 'Key square', value: [0, 1, 2, 3, 4].map((r) => e.square.slice(r * 5, r * 5 + 5).join(' ')).join('  /  ') }, { label: 'Pairs', value: e.digraphs.join(' ') }, { label: 'Encrypted', value: e.output }, { label: 'Decrypted (X fillers stay)', value: d.output }]; },
    limits: 'Pairs hide single-letter frequencies, but pair frequencies still leak. It was broken in practice.', related: ['hill', 'caesar'] },
  { id: 'hill', title: 'Hill Cipher', category: 'Classical', blurb: 'Turns blocks of letters into numbers and multiplies them by a matrix.', tint: 2, tall: false,
    glyph: () => ['ACT', hill('ACT', 'GYBNQKURP')], how: ['Turn letters into numbers: A = 0 … Z = 25.', 'The key is a square matrix (4 letters make 2×2, 9 letters make 3×3).', 'Multiply each block of letters by the matrix and reduce mod 26. To decrypt, multiply by the matrix inverse mod 26.'],
    exampleNote: 'Only matrices whose determinant has no common factor with 26 can be inverted; others are rejected with an explanation.', fields: [{ id: 'key', label: 'Key (4 or 9 letters)', def: 'GYBNQKURP' }, { id: 'text', label: 'Text', def: 'ACT' }],
    run: (v) => { const m = hillMatrix(v.key); const c = hill(v.text, v.key); return [{ label: 'Key matrix', value: m.map((r) => r.join(' ')).join('  /  ') }, { label: 'Encrypted', value: c }, { label: 'Decrypted', value: hill(c, v.key, true) }]; },
    limits: 'It is linear, so a few known plaintext/ciphertext blocks reveal the key.', related: ['playfair', 'aes'] },
  { id: 'des', title: 'DES', category: 'Block cipher', blurb: 'The 16-round Feistel cipher that protected data for decades.', tint: 1, tall: true,
    glyph: () => ['0123456789ABCDEF', desBlock('0123456789ABCDEF', '133457799BBCDFF1').hex], how: ['Rearrange the 64-bit block with a fixed permutation, then split it into a left and right half.', 'Sixteen rounds: expand the right half, mix in a round key, pass it through eight S-boxes, then XOR the result into the left half and swap halves.', 'Apply the final permutation. Decryption is the same process with the round keys in reverse.'],
    exampleNote: 'This is the well-known worked example key and block.', fields: [{ id: 'key', label: 'Key (16 hex digits)', def: '133457799BBCDFF1' }, { id: 'block', label: 'Block (16 hex digits)', def: '0123456789ABCDEF' }],
    run: (v) => { const r = desBlock(v.block, v.key); const back = desBlock(r.hex, v.key, true).hex; return [{ label: 'Ciphertext', value: r.hex }, ...[0, 1, 2, 15].map((i) => ({ label: `After round ${r.rounds[i].round}`, value: `L = ${r.rounds[i].L}, R = ${r.rounds[i].R}` })), { label: 'Decrypted back', value: back }]; },
    limits: 'The 56-bit key is small enough to brute-force. DES is obsolete; AES replaced it.', related: ['aes', 'block'] },
  { id: 'aes', title: 'AES', category: 'Block cipher', blurb: 'The modern standard: 16-byte blocks, 10 to 14 rounds.', tint: 4, tall: false,
    glyph: () => [BLOCK.slice(0, 16), bytesToHex(aesEncryptBlock(hexToBytes(BLOCK), hexToBytes(KEY))).slice(0, 16)], how: ['Load the 16 bytes into a 4×4 grid called the state.', 'Each round: SubBytes (look up each byte in the S-box), ShiftRows (rotate the rows), MixColumns (mix each column), AddRoundKey (XOR with the round key).', 'The last round skips MixColumns. Key size (128/192/256 bits) sets the number of rounds.'],
    exampleNote: 'The FIPS-197 Appendix B example block and key.', fields: [{ id: 'key', label: 'Key (32, 48 or 64 hex digits)', def: KEY }, { id: 'block', label: 'Block (32 hex digits)', def: BLOCK }],
    run: (v) => { const k = hexToBytes(v.key), b = hexToBytes(v.block); if (![16, 24, 32].includes(k.length)) throw new Error(`Key is ${k.length} bytes; AES needs 16, 24 or 32.`); if (b.length !== 16) throw new Error(`Block is ${b.length} bytes; AES encrypts exactly 16.`); return [{ label: 'Key size', value: `AES-${k.length * 8}, ${k.length / 4 + 6} rounds` }, { label: 'Ciphertext', value: bytesToHex(aesEncryptBlock(b, k)) }]; },
    limits: 'No practical attack on full AES is known. Real use also needs a safe mode of operation.', full: { to: '/aes', label: 'Watch every round in 3D' }, related: ['block', 'des'] },
  { id: 'sha512', title: 'SHA-512', category: 'Hashing', blurb: 'Squeezes any input into a fixed 512-bit fingerprint.', tint: 2, tall: true,
    glyph: () => ['abc', 'ddaf35a1…a54ca49f'], how: ['The input is padded and split into 1024-bit blocks.', 'Each block is mixed into a 512-bit internal state over 80 rounds.', 'The final state is the digest. It is one-way: you cannot get the input back from it.'],
    exampleNote: 'Hashing is not encryption; there is no key. The browser computes the digest with its built-in Web Crypto API.', fields: [{ id: 'a', label: 'Input', def: 'hello' }, { id: 'b', label: 'Modified input', def: 'hellp' }],
    run: async (v) => { const [h1, h2] = await Promise.all([sha512Hex(v.a), sha512Hex(v.b)]); return [{ label: 'SHA-512 digest', value: h1 }, { label: 'Size', value: `${h1.length * 4} bits (${h1.length} hex digits)` }, { label: 'Bits that differ for the modified input', value: `${hammingDistance(h1, h2)} / 512` }]; },
    limits: 'For passwords use a slow, salted hash (Argon2, bcrypt), not a bare fast hash.', full: { to: '/sha256', label: 'Open the SHA-256 avalanche lab' }, related: ['block', 'rsa'] },
  { id: 'stream', title: 'Stream Cipher', category: 'Symmetric', blurb: 'Generates a stream of key bytes and XORs it with the message.', tint: 0, tall: false,
    glyph: () => ['Plaintext', bytesToHex(rc4(enc('Key'), enc('Plaintext')).out)], how: ['A key is stretched into a long pseudo-random keystream.', 'XOR each message byte with the matching keystream byte to encrypt.', 'XOR with the same keystream again to decrypt. Never reuse a keystream for two messages.'],
    exampleNote: 'This demo uses RC4, a historic stream cipher, because it is short enough to follow.', fields: [{ id: 'key', label: 'Key', def: 'Key' }, { id: 'text', label: 'Message', def: 'Plaintext' }],
    run: (v) => { if (!v.text) throw new Error('Enter a message.'); const r = rc4(enc(v.key), enc(v.text)); const back = rc4(enc(v.key), r.out).out; return [{ label: 'Keystream (hex)', value: bytesToHex(r.keystream) }, { label: 'Encrypted (hex)', value: bytesToHex(r.out) }, { label: 'Decrypted back', value: new TextDecoder().decode(new Uint8Array(back)) }]; },
    limits: 'RC4 is broken and banned in modern protocols. Today use ChaCha20 or AES in CTR/GCM mode.', related: ['block', 'caesar'] },
  { id: 'block', title: 'Block Cipher Modes', category: 'Block cipher', blurb: 'Why encrypting each block alone leaks patterns, and how chaining fixes it.', tint: 3, tall: true,
    glyph: () => { const k = hexToBytes(KEY), p = hexToBytes('6bc1bee22e409f96e93d7e117393172a'); const e = ecbEncrypt([...p, ...p], k), c = cbcEncrypt([...p, ...p], k, IV); return [`ECB: ${bytesToHex(e[0]).slice(0, 8)} | ${bytesToHex(e[1]).slice(0, 8)}`, `CBC: ${bytesToHex(c[0]).slice(0, 8)} | ${bytesToHex(c[1]).slice(0, 8)}`]; },
    how: ['A block cipher such as AES only handles one 16-byte block. Longer messages need a mode.', 'ECB encrypts every block independently, so identical blocks give identical ciphertext blocks, which reveals patterns.', 'CBC XORs each block with the previous ciphertext block first (the first uses an IV), so repeated blocks no longer look alike.'],
    exampleNote: 'The message below repeats the same 16 bytes three times. Compare how many ciphertext blocks match in each mode. Padding is PKCS#7.', fields: [{ id: 'key', label: 'AES key (32 hex digits)', def: KEY }, { id: 'text', label: 'Message', def: 'SIXTEEN BYTES!!!SIXTEEN BYTES!!!SIXTEEN BYTES!!!' }],
    run: (v) => { const k = hexToBytes(v.key); if (k.length !== 16) throw new Error(`This demo uses AES-128: the key must be 32 hex digits (you gave ${k.length * 2}).`); if (!v.text) throw new Error('Enter a message.'); const d = pkcs7(enc(v.text)); const e = ecbEncrypt(d, k).map(bytesToHex), c = cbcEncrypt(d, k, IV).map(bytesToHex); const dup = (a: string[]) => a.length - new Set(a).size; return [{ label: 'ECB blocks', value: e.map((x) => x.slice(0, 12) + '…').join('  ') }, { label: 'ECB repeated blocks', value: String(dup(e)) }, { label: 'CBC blocks', value: c.map((x) => x.slice(0, 12) + '…').join('  ') }, { label: 'CBC repeated blocks', value: String(dup(c)) }]; },
    limits: 'Never use ECB for real data. Modern systems use authenticated modes such as GCM.', related: ['aes', 'des'] },
  { id: 'rsa', title: 'RSA', category: 'Public key', blurb: 'Lock with a public key, unlock with a private one.', tint: 1, tall: false,
    glyph: () => { const k = rsaKeys(61n, 53n, 17n); return ['65', String(rsaEncrypt(65n, k.e, k.n))]; }, how: ['Pick two primes p and q. Multiply them to get n; compute φ(n) = (p−1)(q−1).', 'Choose e that shares no factor with φ(n); find d so that e·d ≡ 1 (mod φ(n)). Public key: (e, n). Private key: (d, n).', 'Encrypt: c = m^e mod n. Decrypt: m = c^d mod n.'],
    exampleNote: 'Tiny textbook numbers so you can follow the arithmetic.', fields: [{ id: 'p', label: 'Prime p', def: '61' }, { id: 'q', label: 'Prime q', def: '53' }, { id: 'e', label: 'e', def: '17' }, { id: 'm', label: 'Message number (< n)', def: '65' }],
    run: (v) => { const k = rsaKeys(parseBig('p', v.p), parseBig('q', v.q), parseBig('e', v.e)); const c = rsaEncrypt(parseBig('Message', v.m), k.e, k.n); return [{ label: 'n = p × q', value: String(k.n) }, { label: 'φ(n)', value: String(k.phi) }, { label: 'd', value: String(k.d) }, { label: 'Ciphertext', value: String(c) }, { label: 'Decrypted', value: String(rsaDecrypt(c, k.d, k.n)) }]; },
    limits: 'These primes are far too small to be secure. Real RSA uses 2048-bit or larger n plus padding.', full: { to: '/rsa', label: 'Open the modular-exponentiation visualizer' }, related: ['sha512', 'aes'] },
  { id: 'cryptanalysis', title: 'Cryptanalysis', category: 'Attacks', blurb: 'Breaking ciphers by finding structure instead of the key.', tint: 4, tall: true,
    glyph: () => ['KHOOR', caesarBruteForce('KHOOR')[3].text], how: ['Try everything: with a Caesar cipher there are only 26 keys, so brute force finds the answer.', 'Count letters: in English some letters (E, T, A) are far more common. In a simple substitution cipher the most common ciphertext letters point to them.', 'Real attacks target weaknesses in a specific design. These two methods do not threaten modern ciphers.'],
    exampleNote: 'A Caesar-encrypted sentence: read down the candidates until one makes sense.', fields: [{ id: 'ct', label: 'Ciphertext', def: 'WKLV LV D FDHVDU FLSKHU' }],
    run: (v) => { if (!/[a-z]/i.test(v.ct)) throw new Error('Enter ciphertext containing letters.'); const top = [...letterFrequencies(v.ct)].sort((a, b) => b.count - a.count).slice(0, 3).map((t) => `${t.letter}×${t.count}`).join(', '); return [{ label: 'Most common letters', value: top }, ...caesarBruteForce(v.ct).map((c) => ({ label: `Shift ${c.shift}`, value: c.text }))]; },
    limits: 'Frequency analysis needs enough text and a simple cipher. It does not break AES or RSA.', full: { to: '/cryptanalysis', label: 'Open the cryptanalysis workspace' }, related: ['caesar', 'playfair'] },

  { id: 'ecb-attack', title: 'Spot ECB Mode', category: 'Attack Lab', blurb: 'Tell from the ciphertext alone whether a victim used ECB, with no key.', tint: 3, tall: false,
    glyph: () => { const d = pkcs7(enc('ATTACK AT DAWN!!'.repeat(3))); return ['3 identical plaintext blocks', `${repeatedBlocks(ecbEncrypt(d, hexToBytes(KEY)).map(bytesToHex))} repeated ciphertext blocks`]; },
    how: ['The victim encrypts a message with AES, using either ECB or CBC. You only see the ciphertext.', 'Split it into 16-byte blocks and look for identical blocks.', 'ECB gives equal ciphertext for equal plaintext blocks, so any repeat exposes it. CBC does not repeat.'],
    exampleNote: 'The message repeats one 16-byte phrase three times. The detector never sees the key or the plaintext.', fields: [{ id: 'text', label: 'Victim message', def: 'ATTACK AT DAWN!!'.repeat(3) }, { id: 'mode', label: 'Victim mode (ecb or cbc)', def: 'ecb' }],
    run: (v) => { const m = v.mode.trim().toLowerCase(); if (m !== 'ecb' && m !== 'cbc') throw new Error('Mode must be ecb or cbc.'); if (!v.text) throw new Error('Enter a message.'); const d = pkcs7(enc(v.text)), k = hexToBytes(KEY); const ct = (m === 'ecb' ? ecbEncrypt(d, k) : cbcEncrypt(d, k, IV)).map(bytesToHex); const rep = repeatedBlocks(ct); const guess = rep > 0 ? 'ecb' : 'unknown (no repeats: could be CBC, or the message has no repeated blocks)'; return [{ label: 'Attacker sees (blocks)', value: ct.map((x) => x.slice(0, 12) + '…').join('  ') }, { label: 'Repeated blocks', value: String(rep) }, { label: 'Detector says', value: guess }, { label: 'Actual mode', value: m }]; },
    limits: 'No repeats does not prove CBC: a message with no repeated blocks looks random even in ECB. Use authenticated modes such as GCM.', related: ['block', 'two-time-pad'] },
  { id: 'two-time-pad', title: 'Reused Keystream', category: 'Attack Lab', blurb: 'Encrypt two messages with the same stream-cipher key and both fall apart.', tint: 0, tall: true,
    glyph: () => { const x = xorBytes(rc4(enc('Secret'), enc('ATTACK AT DAWN')).out, rc4(enc('Secret'), enc('RETREAT AT DUSK')).out); return ['ATTACK', cribDrag(x, enc('ATTACK'))[0].text]; },
    how: ['A stream cipher XORs the message with a keystream. Reusing the key reuses the keystream.', 'XOR the two ciphertexts: the keystream cancels and you are left with message 1 XOR message 2.', 'Guess a word from message 1 (a crib) and slide it along. Where the guess is right, readable text from message 2 appears.'],
    exampleNote: 'Two messages, one key. The attacker guesses that the first message contains the word ATTACK.', fields: [{ id: 'key', label: 'Shared key', def: 'Secret' }, { id: 'p1', label: 'Message 1', def: 'ATTACK AT DAWN' }, { id: 'p2', label: 'Message 2', def: 'RETREAT AT DUSK' }, { id: 'crib', label: 'Crib (guess from message 1)', def: 'ATTACK' }],
    run: (v) => { if (!v.p1 || !v.p2) throw new Error('Enter both messages.'); const c1 = rc4(enc(v.key), enc(v.p1)).out, c2 = rc4(enc(v.key), enc(v.p2)).out; const x = xorBytes(c1, c2); const hits = cribDrag(x, enc(v.crib)).filter((h) => h.ok).slice(0, 8); return [{ label: 'Ciphertext 1', value: bytesToHex(c1) }, { label: 'Ciphertext 2', value: bytesToHex(c2) }, { label: 'C1 ⊕ C2 equals P1 ⊕ P2', value: String(bytesToHex(x) === bytesToHex(xorBytes(enc(v.p1), enc(v.p2)))) }, ...hits.map((h) => ({ label: `Crib at position ${h.pos} reveals`, value: h.text }))]; },
    limits: 'The attacker never needed the key. Use a fresh nonce for every message; real stream ciphers (ChaCha20, AES-CTR) require one.', related: ['stream', 'ecb-attack'] },
  { id: 'rsa-attack', title: 'Factor Weak RSA', category: 'Attack Lab', blurb: 'Recover a private key from public numbers when the primes are small.', tint: 1, tall: false,
    glyph: () => { const n = 10007n * 10009n; return [`n = ${n}`, '10007 × 10009']; },
    how: ['An attacker sees only the public key (n, e) and the ciphertext c.', 'RSA is safe only if nobody can factor n back into p and q. With small primes, trial division finds them in a moment.', 'Knowing p and q, the attacker computes d exactly as the owner did and decrypts.'],
    exampleNote: 'Primes near 10,000 give a 27-bit modulus. Real keys use moduli of 2048 bits or more.', fields: [{ id: 'p', label: 'Prime p', def: '10007' }, { id: 'q', label: 'Prime q', def: '10009' }, { id: 'e', label: 'e', def: '65537' }, { id: 'm', label: 'Secret number', def: '12345' }],
    run: (v) => { const k = rsaKeys(parseBig('p', v.p), parseBig('q', v.q), parseBig('e', v.e)); const c = rsaEncrypt(parseBig('Secret number', v.m), k.e, k.n); const f = factorSmall(k.n); const d = rsaKeys(f.p, f.q, k.e).d; return [{ label: 'Attacker sees', value: `n = ${k.n}, e = ${k.e}, c = ${c}` }, { label: 'Trial division found', value: `${f.p} × ${f.q} after ${f.steps} steps` }, { label: 'Recovered private d', value: String(d) }, { label: 'Recovered secret', value: String(rsaDecrypt(c, d, k.n)) }]; },
    limits: 'Try larger primes: the attack soon gives up. Real RSA also needs padding (OAEP), which this textbook version lacks.', full: { to: '/rsa', label: 'Open the RSA visualizer' }, related: ['rsa', 'two-time-pad'] },
  { id: 'vigenere-break', title: 'Break Vigenère', category: 'Attack Lab', blurb: 'Recover the key and the message from ciphertext alone using statistics.', tint: 2, tall: true,
    glyph: () => { const r = breakVigenere(vigenere(SAMPLE_ENGLISH, 'LEMON')); return ['key length ?', `${r.length}, key ${r.key}`]; },
    how: ['A repeating key means every nth letter was shifted by the same amount.', 'Try key lengths 1 to 12 and pick the length where those letters look most like English (index of coincidence).', 'Treat each column as a Caesar cipher and choose the shift that best matches English letter frequencies. Together the shifts spell the key.'],
    exampleNote: 'The ciphertext is a paragraph encrypted with the key LEMON. The attacker is not told the key or its length.', fields: [{ id: 'ct', label: 'Ciphertext (at least 60 letters)', def: vigenere(SAMPLE_ENGLISH, 'LEMON') }],
    run: (v) => { const r = breakVigenere(v.ct); return [{ label: 'Estimated key length', value: String(r.length) }, { label: 'Recovered key', value: r.key }, { label: 'Recovered text (start)', value: r.plaintext.slice(0, 120) }]; },
    limits: 'It needs enough text and an English-like message. Short messages or a key as long as the message (a one-time pad) resist it.', full: { to: '/vigenere', label: 'Open the Vigenère visualizer' }, related: ['cryptanalysis', 'caesar'] },
];
export const byId = (id: string) => TOPICS.find((t) => t.id === id);
